version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ottotest_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    command:
      [
        "-source",
        "file:///migrations",
        "-database",
        "postgres://postgres:password@db:5432/ottotest_db?sslmode=disable",
        "up",
      ]
    volumes:
      - ./migrations:/migrations
    links:
      - db
    restart: on-failure

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/ottotest_db?sslmode=disable
    volumes:
      - ./.env:/app/.env

volumes:
  db_data:
